from __future__ import annotations

from pathlib import Path

from brac7.models import Bracket


def export_html(bracket: Bracket, path: Path) -> Path:
    rounds_html = ""
    for rnd in bracket.rounds:
        matches_html = ""
        for m in rnd.matches:
            a = m.display_slot("a", bracket.options)
            b = m.display_slot("b", bracket.options)
            bye_tag = ' <span class="bye-badge">BYE</span>' if m.is_bye else ""
            matches_html += f"""
            <div class="match{' bye' if m.is_bye else ''}">
                <div class="match-id">{m.label or m.id}</div>
                <div class="slots">
                    <div class="slot top">{a}</div>
                    <div class="vs">vs</div>
                    <div class="slot bottom">{b}</div>
                </div>{bye_tag}
            </div>"""
        rounds_html += f"""
        <div class="round">
            <h2>{rnd.name}</h2>
            <div class="matches">{matches_html}
            </div>
        </div>"""

    parts_list = "".join(
        f"<li><span class=\"seed\">#{p.seed}</span> {p.name}</li>"
        for p in bracket.participants
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{bracket.title} — brac7</title>
<style>
  :root {{
    --bg: #0f1419; --panel: #1a2332; --accent: #3d8bfd;
    --text: #e7ecf3; --muted: #8b9cb3; --border: #2a3548;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: "Segoe UI", system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }}
  h1 {{ color: var(--accent); margin-bottom: 0.5rem; }}
  .meta {{ color: var(--muted); margin-bottom: 2rem; font-size: 0.9rem; }}
  .round {{ margin-bottom: 2rem; }}
  .round h2 {{ color: var(--accent); font-size: 1.1rem; margin-bottom: 0.75rem; padding-bottom: 0.3rem; border-bottom: 1px solid var(--border); }}
  .matches {{ display: flex; flex-wrap: wrap; gap: 0.75rem; }}
  .match {{ background: var(--panel); border: 1px solid var(--border); border-radius: 6px; padding: 0.75rem; min-width: 200px; flex: 1 1 200px; }}
  .match.bye {{ border-color: #4a7a4a; }}
  .match-id {{ font-size: 0.75rem; color: var(--muted); margin-bottom: 0.4rem; }}
  .slots {{ display: flex; flex-direction: column; gap: 0.2rem; }}
  .slot {{ font-size: 0.9rem; }}
  .vs {{ font-size: 0.75rem; color: var(--muted); text-align: center; }}
  .bye-badge {{ display: inline-block; background: #2a5a2a; color: #8fbc8f; font-size: 0.7rem; padding: 0.1rem 0.4rem; border-radius: 3px; margin-top: 0.3rem; }}
  .participants {{ background: var(--panel); border: 1px solid var(--border); border-radius: 6px; padding: 1rem; margin-bottom: 2rem; }}
  .participants h2 {{ color: var(--accent); font-size: 1.1rem; margin-bottom: 0.75rem; }}
  .participants ul {{ list-style: none; columns: 3 200px; }}
  .participants li {{ padding: 0.2rem 0; font-size: 0.9rem; }}
  .seed {{ color: var(--muted); font-size: 0.8rem; margin-right: 0.4rem; }}
  .footer {{ color: var(--muted); font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); }}
  a {{ color: var(--accent); }}
  @media (max-width: 600px) {{ body {{ padding: 1rem; }} .participants ul {{ columns: 1; }} .matches {{ flex-direction: column; }} }}
</style>
</head>
<body>
  <h1>{bracket.title}</h1>
  <p class="meta">{bracket.format_label} · {len(bracket.participants)} entrants · bracket size {bracket.size} · {bracket.options.seeding.value}</p>

  <div class="participants">
    <h2>Participants</h2>
    <ul>{parts_list}</ul>
  </div>

  {rounds_html}

  <p class="footer">Generated by <a href="https://github.com/jrb00013/brac7">brac7</a></p>
</body>
</html>"""

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path
